# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb3ea1c5f80ee18367c0c4a46eec272e4769487ac17b2154bcbef03871a23080125939571288f5e9500b31dad1b65d79d2d0f6ce2d68cb4acae9b29f47c3b66

test:
  secret_key_base: 704e237d5114f7fa00d16f83bf71b90388b524fd5985e25f0ba95080ac5fa5c0d8f0ee439bb89253b993e0e844052f01694e82c1b50ab0a129a2c038c20a438d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
