# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c36841a08b46ac3d856d8777f44ff6f050ce3427e61c837f75b3ee62333d96ba75c8e3ce6ee049d5a9c6484809ac25538bab71151d21339dea15404e43676191

test:
  secret_key_base: 3c4f542cb133120574b205da05bda54e3856b344fd78977537c93e4ef1cdc3b6092b3bcaaa8a250991899eeda4a1e5b5cbd1973d8e211a81ce228d9075279ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
